### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by juniorrosul** [lt/PHP-Poly1305#3]
Hi there,

you could put in packagist to facilitate the creation of extensions, for now I will hold a fork in the repository to continue implementation.

tnks.

**Comment by lt** [comment]
Hi,

I'm making a small AEAD library using my ChaCha20 and Poly1305 implementations. 

I'm expecting to tweak a few things in the next couple of days (since they are currently unversioned, I can break whatever I want :)).

After that I'll tag a 0.1 release and put it on Packagist.

**Comment by juniorrosul** [comment]
nice

**Comment by lt** [comment]
[Now on Packagist](https://packagist.org/packages/leigh/poly1305)
